<a href="https://colab.research.google.com/github/JustYuto/DataScienceWithPython/blob/main/NumPy_%E9%80%9F%E7%BF%92.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##単回帰分析の実装（傾きaを求める）

In [ ]:
import numpy as np

In [ ]:
# ベクトルを定義
x=np.array([[1, 2, 3]])
x

array([[1, 2, 3]])

In [ ]:
y=np.array([[2, 3.9, 6.1]])
y

array([[2. , 3.9, 6.1]])

### データの中心化

In [ ]:
#平均の算出: .mean()
x.mean()

2.0

In [ ]:
y.mean()

4.0

In [ ]:
#データの中心化(centering)
xc = x - x.mean()
xc

array([[-1.,  0.,  1.]])

In [ ]:
yc = y - y.mean()
yc

array([[-2. , -0.1,  2.1]])

### aの計算

In [ ]:
#要素積の計算
x * x

array([[1, 4, 9]])

In [ ]:
x

array([[1, 2, 3]])

In [ ]:
#要素積を取ったxの値
xx = xc * xc
xx

array([[1., 0., 1.]])

In [ ]:
xy = xc * yc
xy

array([[ 2. , -0. ,  2.1]])

In [ ]:
#合計: .sum()
xx.sum()

2.0

In [ ]:
xy.sum()

4.1

In [ ]:
# aを算出
a = xy.sum() / xx.sum()
a

2.05