<a href="https://colab.research.google.com/github/JustYuto/DataScienceWithPython/blob/main/%E8%A1%8C%E5%88%97%E6%BC%94%E7%AE%97%E3%81%AE%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##行列演算の基礎

必要な知識

*   ベクトルの定義
*   行列の定義
* 転置
* 逆行列
*行列積




In [ ]:
import numpy as np

In [ ]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [ ]:
x.shape #(行, 列)を表示

(3, 1)

In [ ]:
#行列の定義
X=np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [ ]:
#転置(Transpose)
Xt=X.T
Xt

array([[1, 3],
       [2, 4]])

In [ ]:
#逆行列(linag : linear algebra (線形代数))
X_inv=np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#行列積
XX_inv=np.dot(X, X_inv)
XX_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

## 【補足】NumPyでよく使用する処理

In [ ]:
B = np.array([
              [1,2,3],
              [2,3,4]
])
B

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
row, col = B.shape #行(row)と列(colums)にそれぞれの値を代入

In [ ]:
row

2

In [ ]:
col

3

In [ ]:
for b in B:
  print(b)
  print('--------')

[1 2 3]
--------
[2 3 4]
--------
